name: 'Custom Vault Action'
description: 'My custom Vault action'

inputs:
  role_name:
    description: 'The role name for authentication'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.role_name }}