name: 'Custom Vault Action'
description: 'My custom Vault action'

inputs:
  role_name:
    description: 'The role name for authentication'
    required: true
  namespace:
    description: 'The Vault namespace from which to query secrets. Vault Enterprise only, unset by default'
    required: true
  method:
    description: 'The method to use to authenticate with Vault.'
    default: 'aws'
    required: false
  url:
    description: 'The URL for the vault endpoint'
    required: true
  secrets:
    description: 'A semicolon-separated list of secrets to retrieve. These will automatically be converted to environmental variable keys. See README for more details'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.role_name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.url }}
    - ${{ inputs.secrets}}